### PR TITLE
Fix Image::fromString to support PNG and WebP files

### LINKED ISSUE #30: Failing to create a PNG object from string
The `Image::fromString` method fails when processing PNG files due to infinite recursion. 
The method attempts to call `PNG::fromString($string)` to create a PNG object. However, the PNG class does not implement its own `fromString` method and inherits from the `Image` class. This absence leads to infinite recursion, which will continue until the PHP memory limit is exhausted.

**Error message**
```
Fatal error: Allowed memory size of ... bytes exhausted (tried to allocate ... bytes) in ...
```
**Steps to Reproduce:**

_Warning: will exhaust all memory assigned to PHP_
```
use CSD\Image\Image;

$string = \file_get_contents(__DIR__ . '/Fixtures/nometa.png');
$image = Image::fromString($string); 
```

I will submit a PR for this.

### PR DESCRIPTION
**Pull request by klaari**
- Add missing fromString methods to PNG and WebP classes
- Update Image::fromString to read image size and MIME type with getimagesizefromstring
- Update and refactor related tests

Fixes #30

### CODE REVIEW

**Comment by ilu** [comment]
Thanks @klaari ! @lourot do you have time to review this or should I give it a go?

**Comment by lourot** [comment]
@ilu I have time to review on Thursday but if @klaari needs this to be published already, feel free to merge/publish now and I can still review afterwards :)

For publishing, all you need to do is push a git tag with the new version number after you have merged. See https://docs.frameright.io/php/contributing#releasing

**Comment by lourot** [comment]
(and thanks for the contribution @klaari !)

**Comment by klaari** [comment]
> @ilu I have time to review on Thursday but if @klaari needs this to be published already, feel free to merge/publish now and I can still review afterwards :)

Thanks for the quick reply @ilu & @lourot! This isn't super urgent, publishing this week would be great.

**Comment by ilu** [comment]
@lourot I think it's better you review & publish, but let me know if something comes up and I can take over so we get it out this week 🙌

**Review by lourot — COMMENTED** [review]
@klaari this looks great and I could have merged as is but I spotted an additional issue and maybe we could go the extra-mile and fix it as well. What do you think?
Right now `Image::fromString()` calculates the image size but `PNG::fromString()` and `JPEG::fromFile()` for example don't. I think all these methods should behave the same and calculate the image size. I have added now-failing test assertions to illustrate that. If you agree but have no time, that's perfectly fine, I can also do it. Just let me know.

And thanks a lot for having refactored the tests. It looks way better now!

**Comment by klaari** [comment]
Hi @lourot! Good point, I agree. 
I pushed an update

**Comment by lourot** [comment]
@klaari Thanks a lot! I refactored a bit and will merge and release in a few hours. Please shout if you think I may have missed something.

**Pull request merged**
